app:
  name: "SongLibrary"
  version: "1.0.0"

server:
  port: 8080

log:
  level: "info"

postgres:
  max_pool_size: 20
  conn_attempts: 10
  conn_timeout: 5s

prometheus:
  metrics_port: 9091

music_api:
  url: "http://music-info-api/info"